<a href="<?=App::config('url')?>kupac/novi"
    class="success button expanded">Dodaj novog kupca</a>

<table>
    <thead>
        <tr>
            <th>Ime i prezime</th>
            <th>Email</th>
        
        </tr>
    </thead>
    <tbody>
    <?php foreach($entiteti as $e): ?>
            <tr>
                <td><?=$e->ime?> <?=$e->prezime?></td>
                <td><?=$e->email?></td>
                <td><a href="<?=App::config('url')?>kupac/promjena/<?=$e->sifra?>">Promjena</a> 
                &nbsp;&nbsp;<a href="<?=App::config('url')?>kupac/brisanje/<?=$e->sifra?>" 
                        onclick="return confirm('Sigurno želite obrisati kupca <?= $e->ime . ' ' . $e->prezime ?>?');">Brisanje</a>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>