
<form method="post" action="<?=App::config('url')?>nogometas/promjena/<?= $sifra?>">
  <h4 class="text-center">Detalji nogometaša</h4>

<label>Klub</label>
        <select name="klub" id="klub">
            <?php foreach($klubovi as $k): ?>
                <option
                <?php if($e instanceof stdClass && $e->klub == $k->sifra){
                    echo ' selected=="selected"';
                }
                ?>
                value="<?=$k->sifra?>"><?=$k->ime_kluba?> </option>
            <?php endforeach; ?>
        </select>


  <label>Ime
    <input type="text" name="ime" value="<?=($e instanceof stdClass) ? $e->ime : ''?>" />
  </label>

  <label>Prezime
    <input type="text" name="prezime" value="<?=($e instanceof stdClass) ? $e->prezime : ''?>" />
  </label>

  </label>

  <input type="hidden" name="nova" value="<?=($e instanceof stdClass) ? 0 : 1 ?>" />

  <?=$poruka?>

<div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>nogometas">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
</div>

</form>