<form method="post" 
action="<?=App::config('url')?>nogometas/promjena/<?=$e->sifra?>">
<label for="naziv">Ime nogometaša</label>
<input type="text" name="ime" id="ime" value="<?=$e->ime?>">
<label for="naziv">Prezime nogometaša</label>
<input type="text" name="prezime" id="prezime" value="<?=$e->prezime?>">

<label for="klub">Ekipa</label>
<select name="klub" id="klub">
    <?php foreach($klubovi as $n): ?>
        <option
        <?php if ($e->Klub==$n->sifra){
            echo ' selected="selected"';
        }
        ?>
        value="<?=$n->sifra?>"><?=$n->$ime_kluba?></option>
    <?php endforeach; ?>
    </select>



<?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>nogometas">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>

</form>