<a href="<?=App::config('url')?>nogometas/novi"
    class="success button expanded">Dodaj novog nogometaša</a>

<table>
    <thead>
        <tr>
            <th>Klub</th>
            <th>Ime</th>
            <th>Prezime</th>
        
        </tr>
    </thead>
    <tbody>
    <?php foreach($entiteti as $e): ?>
            <tr>
                <td><?=$e->ime_kluba?></td>
                <td><?=$e->ime?> <?=$e->prezime?></</td>
                <td><a href="<?=App::config('url')?>nogometas/promjena/<?=$e->sifra?>">Promjena</a> 
                &nbsp;&nbsp;<a href="<?=App::config('url')?>nogometas/brisanje/<?=$e->sifra?>" 
                onclick="return confirm('Sigurno želite obrisati kupca <?= $e->ime . ' ' . $e->prezime ?>?');">Brisanje</a>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>