<form method="post" 
action="<?=App::config('url')?>odjeca/promjena/<?=$e->sifra?>">
  
  
  <label>Veličina
    <input type="text" name="velicina" value="<?=$e->velicina?>" />
  </label>

  <label>Boja
    <input type="text" name="boja" value="<?=$e->boja?>" />
  </label>


  <label for="nogometas">Nogometaš</label>
<select name="nogometas" id="nogometas">
    <?php foreach($nogometasi as $n): ?>
        <option
        <?php if ($e->nogometas==$n->sifra){
            echo ' selected="selected"';
        }
        ?>
        value="<?=$n->sifra?>"><?=$n->ime?> <?=$n->prezime?></option>
    <?php endforeach; ?>
</select>

  <label>Cijena
    <input type="text" name="cijena" value="<?=$e->cijena?>" />
  </label>

  <label>Vrsta proizvoda
    <input type="text" name="vrsta_proizvoda" value="<?=$e->vrsta_proizvoda?>" />
  </label>

  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>odjeca">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>


</form>