<form method="post" 
action="<?=App::config('url')?>klub/promjena/<?=$e->sifra?>">
  
  
  <label>ime_kluba
    <input type="text" name="ime_kluba" value="<?=$e->ime_kluba?>" required/>
  </label>

  <label>Stadion
    <input type="text" name="stadion" value="<?=$e->stadion?>" />
  </label>

  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>nba_team">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>


</form>