<a class="success button expanded" 
    href="<?=App::config('url')?>klub/novi">
        Dodaj novi klub
</a>

<table>
    <thead>
        <tr>
            <th>Ime kluba</th>
            <th>Grad</th>
            
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $e): ?>
            <tr>
                <td><?=$e->ime_kluba?> +
                <td><?=$e->grad?></td>
                +
                <td>
                    <a href="<?=App::config('url')?>klub/promjena/<?=$e->sifra?>">Promjena
                     </a>
                    &nbsp;&nbsp;
                    <a href="<?=App::config('url')?>klub/brisanje/<?=$e->sifra?>" 
                        onclick="return confirm('Sigurno želite obrisati odabrani klub <?= $e->ime_kluba . ' ' . $e->grad ?>?');">Brisanje</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>